---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataprepper.gabia.com
  resources:
  - dataprepperclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataprepper.gabia.com
  resources:
  - dataprepperclusters
  - dataprepperpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataprepper.gabia.com
  resources:
  - dataprepperclusters/finalizers
  - dataprepperpipelines/finalizers
  verbs:
  - update
- apiGroups:
  - dataprepper.gabia.com
  resources:
  - dataprepperclusters/status
  - dataprepperpipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
