apiVersion: dataprepper.gabia.com/v1alpha1
kind: DataPrepperClass
metadata:
  labels:
    app.kubernetes.io/name: dataprepper-operator
    app.kubernetes.io/managed-by: kustomize
  name: dataprepperclass-sample
spec:
  # TODO(user): Add fields here
