apiVersion: dataprepper.gabia.com/v1alpha1
kind: DataPrepperClass
metadata:
  labels:
    app.kubernetes.io/name: opensearch-dataprepper-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: dataprepper-2-15
spec:
  image: opensearchproject/data-prepper:2.15.0
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
