apiVersion: dataprepper.gabia.com/v1alpha1
kind: DataPrepperPipeline
metadata:
  name: ha-prepper-pipeline
  namespace: operator-lab
spec:
  clusterRef: ha-prepper
  pipelineYaml: |
    sample-pipeline:
      source:
        http:
          port: 2021
      sink:
        - stdout:
